%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/kevintracy/devel/GravNav/OD_sdr/tle_candidates_v2.txt
%
% Auto-generated by MATLAB on 05-Feb-2021 10:52:55
function tlecandidatesv2 =read_tle_data()
%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "";

% Specify column names and types
opts.VariableNames = "DA";
opts.VariableTypes = "string";
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Import the data
tlecandidatesv2 = readtable("/Users/kevintracy/devel/GravNav/OD_sdr/tle_candidates_v2.txt", opts);

%% Convert to output type
tlecandidatesv2 = table2array(tlecandidatesv2);

%% Clear temporary variables
clear opts
end